title: 李林杰的网站
author: 李林杰
email: linjielig@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  李林杰在学习Github pages是跟着教程制作的一个网站。

# social links
twitter_username: linjielig
github_username:  linjielig

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
